### ISSUE TITLE
Include accessories

### ISSUE THREAD

**Issue by ameyakoshti** [mganjoo/homebridge-leviton-home-away#1]
**Is your feature request related to a problem? Please describe:**

Currently the other plugin to manage accessories does not work well.  https://github.com/tabrindle/homebridge-leviton
It creates warnings such as: This plugin generated a warning from the characteristic 'Brightness': characteristic was supplied illegal value: number 10 exceeded minimum of 30. See https://homebridge.io/w/JtMGR for more info.

Also, the plugin makes close 80k requests per day to fetch the data.

**Describe the solution you'd like:**

Your plugin is a very clean implementation and I was wondering if you can include accessories in it as well.

**Describe alternatives you've considered:**

**Additional context:**

**Comment by mganjoo** [comment]
Hi @ameyakoshti - apologies, I don’t currently have the bandwidth to maintain a plugin for all Leviton accessories (especially as I only own Gen 2 devices and wouldn’t use it personally).

In case you decide to fork a plugin yourself, the actual interaction with the API shouldn’t be too challenging, especially as the API endpoints are relatively well known between this plugin and the other one.
